server:
  port: 9021
  context-path: /QJJZ
  error:
    path: /404
  session:
    timeout: 600

spring:
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    cache: false
  datasource:
#  mssql数据库
#    url: jdbc:sqlserver://localhost;DatebaseName=QJJZ
#    username: sa
#    password: htwater
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  pgsql数据库
    url: jdbc:postgresql://localhost:5432/QJJZ
    username: postgres
    password: JLer
    driver-class-name: org.postgresql.Driver

  jpa:
# Show or not log for each sql query
#    show-sql: true
    hibernate:
# Hibernate ddl auto (create, create-drop, update)
#      ddl-auto: update
# Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
# stripped before adding them to the entity manager)
    properties:
      hibernate:
#      mssql数据库方言
#        dialect: org.hibernate.dialect.SQLServer2008Dialect
#      pgsql数据库方言
        dialect: org.hibernate.dialect.PostgreSQLDialect